import {
  TeamMember,
  Lead,
  LeadActivity,
  Proposal,
  Project,
  Task,
} from '@/types';

// Team Members
export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 'user-kaan',
    name: 'Kaan',
    email: 'kaan@apexkreatif.com',
    role: 'Yönetici',
    phone: '+90 532 000 0001',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    id: 'user-kubilay',
    name: 'Kubilay',
    email: 'kubilay@apexkreatif.com',
    role: 'Yönetici',
    phone: '+90 532 000 0002',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'user-murat',
    name: 'Murat',
    email: 'murat@apexkreatif.com',
    role: 'Satış',
    phone: '+90 532 000 0003',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'user-cem',
    name: 'Cem',
    email: 'cem@apexkreatif.com',
    role: 'Operasyon',
    phone: '+90 532 000 0004',
    avatar_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150',
  },
];

const todayStr = new Date().toISOString().split('T')[0];
const yesterdayStr = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const threeDaysAgoStr = new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0];
const nextWeekStr = new Date(Date.now() + 86400000 * 7).toISOString().split('T')[0];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    company_name: 'Vortex Mimarlık & İç Tasarım',
    sector: 'Mimarlık / İnşaat',
    city_district: 'İstanbul / Kadıköy',
    website: 'https://vortexmimarlik.com',
    instagram: '@vortexmimarlik',
    phone: '+90 533 111 2233',
    email: 'info@vortexmimarlik.com',
    decision_maker: 'Selin Yılmaz (Kurucu Ortak)',
    source_url: 'https://instagram.com/vortexmimarlik',
    priority: 'Yüksek',
    status: 'Görüşme Planlandı',
    assigned_to: 'user-kaan',
    assigned_name: 'Kaan',
    last_contact_date: yesterdayStr,
    next_step_date: todayStr,
    contact_reason: 'Web sitesi yenileme ve 3D render tanıtım videosu',
    recommended_package: 'Web Sitesi + Özel Yazılım + Video Edit',
    first_contact_text: 'Instagram DM üzerinden ulaşıldı, portfolyo incelendi.',
    mini_audit_notes: 'Mevcut site mobilde yavaş ve SSL sertifikası eksik. Instagram görünümü başarılı.',
    estimated_deal_value: 120000,
    win_probability: 75,
    expected_revenue: 90000,
    notes: 'Selin Hanım bütçeyi onayladı, Perşembe Zoom görüşmesinde sözleşme imzalanacak.',
    created_at: threeDaysAgoStr,
    updated_at: todayStr,
  },
  {
    id: 'lead-2',
    company_name: 'DentaCare Ağız ve Diş Sağlığı Polikliniği',
    sector: 'Sağlık / Klinik',
    city_district: 'İstanbul / Ataşehir',
    website: 'https://dentacareklinik.com',
    instagram: '@dentacareatasehir',
    phone: '+90 535 444 5566',
    email: 'iletisim@dentacareklinik.com',
    decision_maker: 'Dr. Mehmet Can',
    source_url: 'Google Haritalar',
    priority: 'Yüksek',
    status: 'Teklif Gönderildi',
    assigned_to: 'user-murat',
    assigned_name: 'Murat',
    last_contact_date: threeDaysAgoStr,
    next_step_date: todayStr,
    contact_reason: 'Online Randevu Dashboard & Sosyal Medya Yönetimi',
    recommended_package: 'Randevu Dashboard\'u + Sosyal Medya Yönetimi',
    first_contact_text: 'Telefon ile görüşüldü, randevu yönetimindeki aksaklıklardan bahsedildi.',
    mini_audit_notes: 'Hastalar WhatsApp üzerinden manuel kaydediliyor, randevu çakışmaları yaşanıyor.',
    estimated_deal_value: 85000,
    win_probability: 60,
    expected_revenue: 51000,
    notes: '85.000 ₺ tutarındaki teklif iletildi. Bugün takip araması yapılacak.',
    created_at: threeDaysAgoStr,
    updated_at: yesterdayStr,
  },
  {
    id: 'lead-3',
    company_name: 'Natura Organik Gıda & Kafe',
    sector: 'Restoran / Kafe',
    city_district: 'İstanbul / Beşiktaş',
    website: 'https://naturagida.com',
    instagram: '@naturagidakafe',
    phone: '+90 536 777 8899',
    email: 'siparis@naturagida.com',
    decision_maker: 'Caner Aksoy',
    source_url: 'Google Sheets İçe Aktarım',
    priority: 'Orta',
    status: 'İlk Temas',
    assigned_to: 'user-kubilay',
    assigned_name: 'Kubilay',
    last_contact_date: yesterdayStr,
    next_step_date: nextWeekStr,
    contact_reason: 'Sosyal Medya Çekim & Video Edit',
    recommended_package: 'Çekim + Video Edit + Marka Kimliği',
    first_contact_text: 'WhatsApp üzerinden katalog iletildi.',
    mini_audit_notes: 'Reels videoları düşük çözünürlüklü, marka kurumsal dili zayıf.',
    estimated_deal_value: 45000,
    win_probability: 40,
    expected_revenue: 18000,
    notes: 'Yeni menü lansmanı öncesinde Reels paketi önerildi.',
    created_at: yesterdayStr,
    updated_at: yesterdayStr,
  },
  {
    id: 'lead-4',
    company_name: 'Solaria Enerji Sistemleri',
    sector: 'Yenilenebilir Enerji',
    city_district: 'Ankara / Çankaya',
    website: 'https://solariaenerji.com',
    instagram: '@solariaenerji',
    phone: '+90 532 999 0011',
    email: 'proje@solariaenerji.com',
    decision_maker: 'Engin Solmaz (Genel Müdürü)',
    source_url: 'Referans (Mevcut Müşteri)',
    priority: 'Yüksek',
    status: 'Kazanıldı',
    assigned_to: 'user-kaan',
    assigned_name: 'Kaan',
    last_contact_date: yesterdayStr,
    next_step_date: nextWeekStr,
    contact_reason: 'B2B Kurumsal Web Portal & Özel Güneş Santrali Hesaplayıcı Yazılım',
    recommended_package: 'Web Sitesi + Özel Yazılım',
    first_contact_text: 'Yüz yüze görüşme gerçekleştirildi.',
    mini_audit_notes: 'Mevcut site 2018 kalma, mobille uyumsuz. Hesap makinesi modülü şart.',
    estimated_deal_value: 190000,
    win_probability: 100,
    expected_revenue: 190000,
    notes: 'Sözleşme imzalandı, ilk taksit 95.000 ₺ tahsil edildi. Proje başlatıldı.',
    created_at: threeDaysAgoStr,
    updated_at: yesterdayStr,
  },
  {
    id: 'lead-5',
    company_name: 'Luxe Stay Butik Otel',
    sector: 'Turizm / Otelcilik',
    city_district: 'Muğla / Bodrum',
    website: 'https://luxestaybodrum.com',
    instagram: '@luxestaybodrum',
    phone: '+90 530 123 4567',
    email: 'reservation@luxestaybodrum.com',
    decision_maker: 'Aylin Alkan',
    source_url: 'Instagram Reklamı',
    priority: 'Düşük',
    status: 'Yeni',
    assigned_to: 'user-cem',
    assigned_name: 'Cem',
    last_contact_date: undefined,
    next_step_date: todayStr,
    contact_reason: 'Sezon öncesi Dijital Pazarlama ve Marka Kimliği',
    recommended_package: 'Marka Kimliği + Sosyal Medya Yönetimi',
    first_contact_text: 'Henüz ilk temas yapılmadı.',
    mini_audit_notes: 'Booking.com puanları yüksek ancak doğrudan web rezervasyon altyapıları yok.',
    estimated_deal_value: 60000,
    win_probability: 30,
    expected_revenue: 18000,
    notes: 'Bugün aranıp ilk temas kurulacak.',
    created_at: todayStr,
    updated_at: todayStr,
  },
];

export const INITIAL_ACTIVITIES: LeadActivity[] = [
  {
    id: 'act-1',
    lead_id: 'lead-1',
    user_id: 'user-kaan',
    user_name: 'Kaan',
    type: 'Toplantı',
    description: 'Selin Hanım ile Zoom toplantısı yapıldı. Web sitesi yenileme ve 3D video edit paketi sunuldu.',
    created_at: yesterdayStr,
  },
  {
    id: 'act-2',
    lead_id: 'lead-2',
    user_id: 'user-murat',
    user_name: 'Murat',
    type: 'Teklif Gönderildi',
    description: 'Dr. Mehmet Can için 85.000 ₺ tutarında Randevu Dashboard teklif dokümanı iletildi.',
    created_at: threeDaysAgoStr,
  },
  {
    id: 'act-3',
    lead_id: 'lead-4',
    user_id: 'user-kaan',
    user_name: 'Kaan',
    type: 'Durum Değişikliği',
    description: 'Solaria Enerji projesi onaylandı! Durum "Kazanıldı" olarak güncellendi ve proje başlatıldı.',
    created_at: yesterdayStr,
  },
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-1',
    lead_id: 'lead-2',
    lead_name: 'DentaCare Ağız ve Diş Sağlığı',
    title: 'DentaCare Diş Kliniği Randevu Dashboard & Dijital Yönetim Teklifi',
    service_package: 'Randevu Dashboard\'u + Sosyal Medya Yönetimi',
    amount: 85000,
    date_sent: threeDaysAgoStr,
    valid_until: nextWeekStr,
    status: 'Gönderildi',
    estimated_close_date: todayStr,
    notes: 'Klinik randevu yazılımı ve 6 aylık sosyal medya içerik üretimi dahildir.',
    follow_up_reminder_date: todayStr,
    created_by: 'user-murat',
    created_at: threeDaysAgoStr,
  },
  {
    id: 'prop-2',
    lead_id: 'lead-1',
    lead_name: 'Vortex Mimarlık & İç Tasarım',
    title: 'Vortex Mimarlık Web Portal & 3D Render Video Çekim Teklifi',
    service_package: 'Web Sitesi + Özel Yazılım + Video Edit',
    amount: 120000,
    date_sent: yesterdayStr,
    valid_until: nextWeekStr,
    status: 'Revizyon',
    estimated_close_date: nextWeekStr,
    notes: '3D Render animasyonu kapsamı revize edildi.',
    follow_up_reminder_date: nextWeekStr,
    created_by: 'user-kaan',
    created_at: yesterdayStr,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    lead_id: 'lead-4',
    proposal_id: 'prop-3',
    project_name: 'Solaria Enerji B2B Portal & Güneş Hesaplayıcı',
    client_name: 'Solaria Enerji Sistemleri',
    service_type: 'Web Sitesi + Özel Yazılım',
    assigned_to: 'user-cem',
    assigned_name: 'Cem',
    start_date: yesterdayStr,
    deadline: nextWeekStr,
    status: 'Devam Ediyor',
    total_fee: 190000,
    payment_status: 'Kısmi Ödendi',
    files_or_links: 'https://figma.com/file/solaria-portal-design',
    client_notes: 'Güneş santrali KW hesaplayıcı modülü öncelikli teslim edilecek.',
    created_at: yesterdayStr,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'DentaCare Dr. Mehmet Bey teklif takip araması yap',
    lead_id: 'lead-2',
    assigned_to: 'user-murat',
    assigned_name: 'Murat',
    due_date: todayStr,
    priority: 'Yüksek',
    status: 'Yapılacak',
    created_at: yesterdayStr,
  },
  {
    id: 'task-2',
    title: 'Vortex Mimarlık Zoom toplantı sunumu ve taslak Figma linki hazırla',
    lead_id: 'lead-1',
    assigned_to: 'user-kaan',
    assigned_name: 'Kaan',
    due_date: todayStr,
    priority: 'Yüksek',
    status: 'Devam Ediyor',
    created_at: yesterdayStr,
  },
  {
    id: 'task-3',
    title: 'Luxe Stay Bodrum ilk temas aramasını gerçekleştir',
    lead_id: 'lead-5',
    assigned_to: 'user-cem',
    assigned_name: 'Cem',
    due_date: todayStr,
    priority: 'Orta',
    status: 'Yapılacak',
    created_at: todayStr,
  },
];

// Helper to get or initialize local storage state
export function getStoredData<T>(key: string, initialData: T): T {
  if (typeof window === 'undefined') return initialData;
  try {
    const item = localStorage.getItem(`apex_kreatif_${key}`);
    return item ? JSON.parse(item) : initialData;
  } catch (error) {
    console.error(`Error reading ${key} from localStorage:`, error);
    return initialData;
  }
}

export function setStoredData<T>(key: string, value: T): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(`apex_kreatif_${key}`, JSON.stringify(value));
  } catch (error) {
    console.error(`Error saving ${key} to localStorage:`, error);
  }
}
