'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Shell } from '@/components/layout/Shell';
import { createClient, isSupabaseConfigured } from '@/lib/supabase/client';
import { LifecycleAction, Project } from '@/types';
import { HeartHandshake, Plus } from 'lucide-react';

export default function LifecyclePage() {
 const supabase=createClient(); const configured=isSupabaseConfigured(); const [projects,setProjects]=useState<Project[]>([]); const [actions,setActions]=useState<LifecycleAction[]>([]); const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{if(!configured)return;const [p,a]=await Promise.all([supabase.from('projects').select('*').is('archived_at',null).order('updated_at',{ascending:false}),supabase.from('crm_lifecycle_actions').select('*').order('due_date',{ascending:true})]);if(p.data)setProjects(p.data as Project[]);if(a.data)setActions(a.data as LifecycleAction[])},[configured,supabase]);useEffect(()=>{load()},[load]);
 const projectById=useMemo(()=>new Map(projects.map(p=>[p.id,p])),[projects]);
 const add=async(project:Project,type:LifecycleAction['action_type'])=>{setSaving(true);const due=new Date();due.setDate(due.getDate()+7);const {error}=await supabase.from('crm_lifecycle_actions').insert({project_id:project.id,action_type:type,due_date:due.toISOString().slice(0,10),notes:''});setSaving(false);if(error)alert(error.message);else load()};
 const setStatus=async(a:LifecycleAction,status:LifecycleAction['status'])=>{const {error}=await supabase.from('crm_lifecycle_actions').update({status}).eq('id',a.id);if(error)alert(error.message);else load()};
 return <Shell><div className="space-y-6"><div><h1 className="text-2xl font-extrabold text-white">Müşteri Yaşam Döngüsü</h1><p className="text-xs text-apex-muted mt-1">Teslimden sonra yenileme, çapraz satış, referans ve memnuniyet takibini unutmayın.</p></div>
 <section className="bg-apex-card border border-apex-border rounded-xl p-5"><h2 className="font-bold text-white">Açık takipler</h2><div className="space-y-2 mt-4">{actions.filter(a=>a.status==='Bekliyor').length?actions.filter(a=>a.status==='Bekliyor').map(a=><div key={a.id} className="bg-apex-dark border border-apex-border rounded-lg p-3 flex items-center gap-3"><HeartHandshake className="w-4 h-4 text-apex-orange"/><div className="flex-1"><p className="text-sm text-white font-bold">{a.action_type} · {projectById.get(a.project_id||'')?.client_name || 'Müşteri'}</p><p className="text-[11px] text-apex-muted">{a.due_date} {a.notes ? `· ${a.notes}`:''}</p></div><button onClick={()=>setStatus(a,'Tamamlandı')} className="text-xs text-emerald-400 border border-emerald-500/30 rounded px-3 py-1.5">Tamamla</button><button onClick={()=>setStatus(a,'Atlandı')} className="text-xs text-apex-muted border border-apex-border rounded px-3 py-1.5">Atla</button></div>):<p className="text-xs text-apex-muted py-3">Açık takip yok.</p>}</div></section>
 <section className="bg-apex-card border border-apex-border rounded-xl p-5"><h2 className="font-bold text-white">Müşteriye yeni takip ekle</h2><div className="grid grid-cols-1 lg:grid-cols-2 gap-2 mt-4">{projects.map(p=><div key={p.id} className="bg-apex-dark border border-apex-border rounded-lg p-3"><p className="font-bold text-sm text-white">{p.client_name}</p><p className="text-[11px] text-apex-muted mb-3">{p.project_name} · {p.status}</p><div className="flex flex-wrap gap-2">{(['Yenileme','Çapraz Satış','Referans','Memnuniyet'] as const).map(type=><button disabled={saving} onClick={()=>add(p,type)} key={type} className="text-[11px] border border-apex-border hover:border-apex-orange rounded px-2 py-1.5 text-apex-muted hover:text-white"><Plus className="inline w-3 h-3"/> {type}</button>)}</div></div>)}</div></section></div></Shell>
}
