'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Briefcase, Clapperboard, FileText, Megaphone, WalletCards } from 'lucide-react';
import { Shell } from '@/components/layout/Shell';
import { AdCampaign, ClientBrand, ContentItem, Lead, Payment, Project, Proposal } from '@/types';
import { createClient } from '@/lib/supabase/client';
import { formatCurrency, formatDate } from '@/lib/utils';

export default function BrandDetailPage({ params }: { params: { id: string } }) {
  const supabase=createClient(); const [brand,setBrand]=useState<ClientBrand|null>(null); const [lead,setLead]=useState<Lead|null>(null); const [projects,setProjects]=useState<Project[]>([]); const [proposals,setProposals]=useState<Proposal[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [content,setContent]=useState<ContentItem[]>([]); const [ads,setAds]=useState<AdCampaign[]>([]); const [error,setError]=useState('');
  const load=useCallback(async()=>{const {data:b,error:e}=await supabase.from('client_brands').select('*').eq('id',params.id).single();if(e||!b){setError('Müşteri dosyası bulunamadı.');return;}const item=b as ClientBrand;setBrand(item);const [l,p,pr,c,a]=await Promise.all([item.lead_id?supabase.from('leads').select('*').eq('id',item.lead_id).maybeSingle():Promise.resolve({data:null}),supabase.from('projects').select('*').or(`lead_id.eq.${item.lead_id||'00000000-0000-0000-0000-000000000000'},id.eq.${item.project_id||'00000000-0000-0000-0000-000000000000'}`).order('created_at',{ascending:false}),item.lead_id?supabase.from('proposals').select('*').eq('lead_id',item.lead_id).order('created_at',{ascending:false}):Promise.resolve({data:[]}),supabase.from('content_items').select('*').eq('brand_name',item.company_name).order('created_at',{ascending:false}),supabase.from('ad_campaigns').select('*').or(`lead_id.eq.${item.lead_id||'00000000-0000-0000-0000-000000000000'},project_id.eq.${item.project_id||'00000000-0000-0000-0000-000000000000'}`)]);if(l.data)setLead(l.data as Lead);const ps=(p.data||[]) as Project[];setProjects(ps);if(pr.data)setProposals(pr.data as Proposal[]);if(c.data)setContent(c.data as ContentItem[]);if(a.data)setAds(a.data as AdCampaign[]);if(ps.length){const ids=ps.map(x=>x.id);const pay=await supabase.from('payments').select('*').in('project_id',ids).order('due_date');if(pay.data)setPayments(pay.data as Payment[]);}},[params.id,supabase]);
  useEffect(()=>{const safeLoad=async()=>{const {data:b,error:brandError}=await supabase.from('client_brands').select('*').eq('id',params.id).single();if(brandError||!b){setError('Müşteri dosyası bulunamadı.');return;}const item=b as ClientBrand;setBrand(item);const empty='00000000-0000-0000-0000-000000000000';const [leadResult,projectResult,proposalResult,contentResult,adsResult]=await Promise.all([item.lead_id?supabase.from('leads').select('*').eq('id',item.lead_id).maybeSingle():Promise.resolve({data:null,error:null}),supabase.from('projects').select('*').or(`lead_id.eq.${item.lead_id||empty},id.eq.${item.project_id||empty}`).order('created_at',{ascending:false}),item.lead_id?supabase.from('proposals').select('*').eq('lead_id',item.lead_id).order('created_at',{ascending:false}):Promise.resolve({data:[],error:null}),supabase.from('content_items').select('*').eq('client_brand_id',params.id).order('created_at',{ascending:false}),supabase.from('ad_campaigns').select('*').or(`lead_id.eq.${item.lead_id||empty},project_id.eq.${item.project_id||empty}`)]);if(leadResult.error||projectResult.error||proposalResult.error||contentResult.error||adsResult.error){setError('Müşteri dosyasının bağlı verileri yüklenemedi. Bağlantıyı ve son veritabanı güncellemesini kontrol edin.');return;}const linkedProjects=(projectResult.data||[]) as Project[];let linkedPayments:Payment[]=[];if(linkedProjects.length){const paymentResult=await supabase.from('payments').select('*').in('project_id',linkedProjects.map(project=>project.id)).order('due_date');if(paymentResult.error){setError('Müşteri tahsilatları yüklenemedi. Lütfen tekrar deneyin.');return;}linkedPayments=(paymentResult.data||[]) as Payment[];}if(leadResult.data)setLead(leadResult.data as Lead);setProjects(linkedProjects);setProposals((proposalResult.data||[]) as Proposal[]);setContent((contentResult.data||[]) as ContentItem[]);setAds((adsResult.data||[]) as AdCampaign[]);setPayments(linkedPayments);setError('');};safeLoad();},[params.id,supabase]);
  const finance=useMemo(()=>payments.reduce((x,p)=>{const paid=p.status==='Tamamlandı'?Number(p.amount):Number(p.paid_amount)||0;return{planned:x.planned+Number(p.amount),paid:x.paid+paid}}, {planned:0,paid:0}),[payments]);
  if(error)return <Shell><p className="text-red-300">{error}</p></Shell>; if(!brand)return <Shell><p className="text-apex-muted">Müşteri dosyası yükleniyor…</p></Shell>;
  return <Shell><div className="space-y-5"><Link href="/brands" className="inline-flex items-center gap-2 text-xs text-apex-muted hover:text-white"><ArrowLeft className="w-4 h-4"/>Müşterilere dön</Link><section className="bg-apex-card border border-apex-border rounded-2xl p-6"><p className="text-apex-orange text-xs font-bold uppercase">Tek müşteri dosyası</p><h1 className="text-3xl font-black text-white mt-1">{brand.company_name}</h1><p className="text-sm text-apex-muted mt-2">{brand.sector||lead?.sector||'Sektör belirtilmedi'} · {brand.contact_name||lead?.decision_maker||'Yetkili belirtilmedi'}</p><div className="flex flex-wrap gap-3 mt-5 text-xs"><span>{brand.contact_phone||lead?.phone||'Telefon yok'}</span><span>{brand.contact_email||lead?.email||'E-posta yok'}</span>{(brand.website||lead?.website)&&<a className="text-apex-orange" href={brand.website||lead?.website} target="_blank" rel="noreferrer">Web sitesi</a>}</div></section>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Summary icon={Briefcase} label="Projeler" value={String(projects.length)}/><Summary icon={FileText} label="Teklifler" value={String(proposals.length)}/><Summary icon={WalletCards} label="Tahsilat" value={`${formatCurrency(finance.paid)} / ${formatCurrency(finance.planned)}`}/><Summary icon={Megaphone} label="Reklamlar" value={String(ads.length)}/></div>
  <div className="grid lg:grid-cols-2 gap-4"><Panel title="Projeler"><Rows empty="Henüz proje yok." rows={projects.map(p=>({title:p.project_name,sub:`${p.status} · ${formatDate(p.deadline)}`,href:'/projects'}))}/></Panel><Panel title="Teklifler"><Rows empty="Henüz teklif yok." rows={proposals.map(p=>({title:p.title,sub:`${p.status} · ${formatCurrency(Number(p.amount))}`,href:'/proposals'}))}/></Panel><Panel title="İçerik üretimi"><Rows empty="Bu markaya bağlı içerik yok." rows={content.map(c=>({title:c.title,sub:`${c.format} · ${c.stage}`,href:'/content'}))}/></Panel><Panel title="Reklam performansı"><Rows empty="Bu müşteriye bağlı kampanya yok." rows={ads.map(a=>({title:a.name,sub:`${a.platform} · ${a.status} · ${formatCurrency(Number(a.spend))}`,href:'/ads'}))}/></Panel></div>
  </div></Shell>;
}
function Summary({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string}){return <div className="bg-apex-card border border-apex-border rounded-xl p-4"><Icon className="w-4 h-4 text-apex-orange"/><p className="text-[10px] text-apex-muted mt-3">{label}</p><p className="text-sm font-bold text-white mt-1">{value}</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="bg-apex-card border border-apex-border rounded-2xl p-5"><h2 className="font-bold text-white">{title}</h2><div className="mt-3 space-y-2">{children}</div></section>}
function Rows({rows,empty}:{rows:{title:string;sub:string;href:string}[];empty:string}){return rows.length?<>{rows.slice(0,6).map((r,i)=><Link key={`${r.title}-${i}`} href={r.href} className="block bg-apex-dark rounded-lg p-3 hover:ring-1 hover:ring-apex-orange"><p className="text-xs font-bold text-white">{r.title}</p><p className="text-[10px] text-apex-muted mt-1">{r.sub}</p></Link>)}</>:<p className="text-xs text-apex-muted py-4">{empty}</p>}
