'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { Shell } from '@/components/layout/Shell';
import { createClient, isSupabaseConfigured } from '@/lib/supabase/client';
import { CrmDocument, Lead } from '@/types';
import { Copy, ExternalLink, Save, Share2 } from 'lucide-react';

const defaults = (lead: Lead) => ({ title: `${lead.company_name} · çalışma planı`, client: lead.company_name, summary: `Bu alan, ${lead.company_name} için onaylanmış kapsam, teslimler, bağlantılar ve geri bildirimleri tek yerde toplar. Göndermeden önce aşağıdaki taslağı görüşme sonucuna göre düzenleyin.`, deliverables: (lead.recommended_package || 'Hizmet kapsamı görüşmede netleştirilecek').split(/\n|\+/).map(x=>x.trim()).filter(Boolean), milestones: ['Kapsam ve teklif onayı', 'Üretim / tasarım başlangıcı', 'Müşteri geri bildirimi ve revizyon', 'Teslim ve kapanış'], links: [] as {label:string;url:string}[] });
export default function WorkspacePage() {
 const supabase=createClient(); const configured=isSupabaseConfigured(); const [leads,setLeads]=useState<Lead[]>([]); const [leadId,setLeadId]=useState(''); const [doc,setDoc]=useState<CrmDocument|null>(null); const [content,setContent]=useState<Record<string,unknown>>({}); const [status,setStatus]=useState('');
 const load=useCallback(async()=>{if(!configured)return; const {data}=await supabase.from('leads').select('*').is('archived_at',null).order('company_name'); if(data)setLeads(data as Lead[]);},[configured,supabase]); useEffect(()=>{load();},[load]);
 const select=async(id:string)=>{setLeadId(id);setDoc(null);setStatus(''); const lead=leads.find(l=>l.id===id); if(!lead)return; const {data}=await supabase.from('crm_documents').select('*').eq('entity_type','lead').eq('entity_id',id).maybeSingle(); if(data){const d=data as CrmDocument;setDoc(d);setContent(d.content);}else setContent(defaults(lead));};
 const save=async()=>{if(!leadId)return;const {data,error}=await supabase.rpc('crm_save_document',{p_type:'lead',p_id:leadId,p_content:content,p_revision:doc?.revision||1});if(error){setStatus(error.message);return;}const next=data as CrmDocument;setDoc(next);setContent(next.content);setStatus('Kaydedildi.');};
 const publish=async()=>{if(!doc){await save();return setStatus('Önce kaydedin, sonra paylaşın.');}const {data,error}=await supabase.rpc('crm_publish',{p_document:doc.id,p_public:content});if(error){setStatus(error.message);return;}const url=`${window.location.origin}/portal/${data}`;await navigator.clipboard.writeText(url);setStatus('Müşteri bağlantısı panoya kopyalandı. Bağlantı 30 gün geçerlidir ve yalnızca bu belgeyi gösterir.');};
 const text=(key:string)=>(content[key] as string)||''; const change=(key:string,value:string)=>setContent({...content,[key]:key==='deliverables'||key==='milestones'?value.split('\n').map(x=>x.trim()).filter(Boolean):value});
 return <Shell><div className="max-w-5xl space-y-6"><div><p className="text-apex-orange text-xs font-bold uppercase tracking-widest">Müşteri çalışma alanı</p><h1 className="text-2xl font-black text-white">Teklif, teslim ve geri bildirim tek yerde</h1><p className="text-xs text-apex-muted mt-2">Paylaşmadan önce müşteriyle ilgili olmayan iç notları bu alana yazmayın. Bu alanın geçmişi kaydedilir; her bağlantı iptal edilebilir.</p></div><section className="bg-apex-card border border-apex-border rounded-2xl p-5 space-y-4"><select value={leadId} onChange={e=>select(e.target.value)} className="w-full bg-apex-dark border border-apex-border rounded-lg p-3 text-white"><option value="">Müşteri adayı seçin</option>{leads.map(lead=><option key={lead.id} value={lead.id}>{lead.company_name}</option>)}</select>{leadId&&<><input value={text('title')} onChange={e=>change('title',e.target.value)} className="w-full bg-apex-dark border border-apex-border rounded-lg p-3 font-bold text-white" placeholder="Başlık"/><textarea value={text('summary')} onChange={e=>change('summary',e.target.value)} className="w-full min-h-28 bg-apex-dark border border-apex-border rounded-lg p-3 text-sm text-white" placeholder="Müşteri için özet"/><div className="grid md:grid-cols-2 gap-4"><div><label className="text-xs text-apex-muted">Teslimler (satır satır)</label><textarea value={Array.isArray(content.deliverables)?content.deliverables.join('\n'):''} onChange={e=>change('deliverables',e.target.value)} className="mt-1 w-full min-h-32 bg-apex-dark border border-apex-border rounded-lg p-3 text-sm text-white"/></div><div><label className="text-xs text-apex-muted">Süreç / ödeme adımları (satır satır)</label><textarea value={Array.isArray(content.milestones)?content.milestones.join('\n'):''} onChange={e=>change('milestones',e.target.value)} className="mt-1 w-full min-h-32 bg-apex-dark border border-apex-border rounded-lg p-3 text-sm text-white"/></div></div><div className="flex flex-wrap gap-3"><button onClick={save} className="px-4 py-2 bg-apex-dark border border-apex-border rounded-lg text-sm text-white flex items-center gap-2"><Save className="w-4 h-4"/>Kaydet</button><button onClick={publish} className="px-4 py-2 bg-apex-orange rounded-lg text-sm font-bold text-white flex items-center gap-2"><Share2 className="w-4 h-4"/>Müşteriyle paylaş</button>{status&&<p className="text-xs text-apex-orange self-center">{status}</p>}</div></>}</section></div></Shell>;
}
