'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { Shell } from '@/components/layout/Shell';
import { Lead } from '@/types';
import { createClient, isSupabaseConfigured } from '@/lib/supabase/client';
import { Mail, MessageCircle } from 'lucide-react';

export default function OutreachPage() {
  const supabase = createClient(); const configured = isSupabaseConfigured();
  const [leads,setLeads]=useState<Lead[]>([]); const [leadId,setLeadId]=useState(''); const [channel,setChannel]=useState<'email'|'whatsapp'>('email'); const [subject,setSubject]=useState('APEX KREATİF — Dijital görünürlüğünüz için kısa öneri'); const [message,setMessage]=useState('Merhaba,\n\nMarkanızı kısaca inceledik. Web sitesi, sosyal medya ve müşteri akışı tarafında geliştirebileceğimiz birkaç fırsat gördük. Uygunsanız size kısa bir mini denetim paylaşmak isteriz.\n\nAPEX KREATİF'); const [sending,setSending]=useState(false); const [result,setResult]=useState('');
  const load=useCallback(async()=>{if(!configured)return;const {data}=await supabase.from('leads').select('*').neq('status','Kaybedildi').order('company_name');if(data)setLeads(data as Lead[]);},[configured,supabase]); useEffect(()=>{load();},[load]);
  const selected=leads.find(item=>item.id===leadId);
  const send=async(event:React.FormEvent)=>{event.preventDefault();if(!selected)return;const to=channel==='email'?selected.email:selected.phone;if(!to){setResult(channel==='email'?'Bu adayda e-posta yok.':'Bu adayda telefon yok.');return;}setSending(true);setResult('');const response=await fetch(`/api/outreach/${channel}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(channel==='email'?{leadId,to,subject,text:message}:{leadId,to,text:message})});const data=await response.json().catch(()=>({}));setSending(false);setResult(response.ok?'Mesaj gönderildi ve aday geçmişine kaydedildi.':data.error||'Gönderim başarısız oldu.');};
  return <Shell><div className="max-w-3xl space-y-6"><div><h1 className="text-2xl font-extrabold text-white">E-posta & WhatsApp Gönderimi</h1><p className="text-xs text-apex-muted mt-1">Bağlantı anahtarları Railway’e girildiğinde mesajlar bu ekrandan güvenli biçimde gönderilir.</p></div><form onSubmit={send} className="bg-apex-card border border-apex-border rounded-2xl p-6 space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div><label className="block text-xs text-apex-muted mb-1">Müşteri adayı</label><select required value={leadId} onChange={e=>setLeadId(e.target.value)} className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"><option value="">Seçin</option>{leads.map(lead=><option key={lead.id} value={lead.id}>{lead.company_name}</option>)}</select></div><div><label className="block text-xs text-apex-muted mb-1">Kanal</label><select value={channel} onChange={e=>setChannel(e.target.value as 'email'|'whatsapp')} className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"><option value="email">E-posta</option><option value="whatsapp">WhatsApp</option></select></div></div>{selected&&<p className="text-xs text-apex-orange">Alıcı: {channel==='email'?(selected.email||'E-posta yok'):(selected.phone||'Telefon yok')}</p>}{channel==='email'&&<div><label className="block text-xs text-apex-muted mb-1">Konu</label><input value={subject} onChange={e=>setSubject(e.target.value)} maxLength={160} className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"/></div>}<div><label className="block text-xs text-apex-muted mb-1">Mesaj</label><textarea required rows={10} value={message} onChange={e=>setMessage(e.target.value)} maxLength={channel==='email'?5000:4096} className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"/></div>{result&&<p className="text-xs text-apex-orange">{result}</p>}<button disabled={sending} className="flex items-center gap-2 bg-apex-orange disabled:opacity-60 text-white text-xs font-bold px-4 py-2.5 rounded-lg">{channel==='email'?<Mail className="w-4 h-4"/>:<MessageCircle className="w-4 h-4"/>}{sending?'Gönderiliyor...':channel==='email'?'E-posta Gönder':'WhatsApp Gönder'}</button></form><div className="bg-apex-card border border-apex-border rounded-xl p-5 text-xs text-apex-muted"><strong className="text-white">Bağlamak için:</strong> Railway Variables bölümüne `.env.example` içindeki Resend ve Meta WhatsApp değişkenlerini ekleyin. Anahtarlar yalnızca sunucuda kullanılır.</div></div></Shell>;
}
