'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Shell } from '@/components/layout/Shell';
import { AgencyGoal, BusinessExpense, Lead, Payment, Proposal } from '@/types';
import { createClient, isSupabaseConfigured } from '@/lib/supabase/client';
import { formatCurrency } from '@/lib/utils';
import { Save } from 'lucide-react';

const monthStart = () => new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10);
const inCurrentMonth = (date?: string) => Boolean(date && date.slice(0, 7) === monthStart().slice(0, 7));

export default function ReportsPage() {
  const supabase = createClient(); const configured = isSupabaseConfigured();
  const [payments, setPayments] = useState<Payment[]>([]); const [expenses, setExpenses] = useState<BusinessExpense[]>([]); const [leads, setLeads] = useState<Lead[]>([]); const [proposals, setProposals] = useState<Proposal[]>([]);
  const [goal, setGoal] = useState<Partial<AgencyGoal>>({ month_start: monthStart(), revenue_target: 0, new_lead_target: 0, proposal_target: 0, notes: '' });
  const load = useCallback(async () => { if (!configured) return; const [p,e,l,pr,g] = await Promise.all([supabase.from('payments').select('*'),supabase.from('business_expenses').select('*'),supabase.from('leads').select('*'),supabase.from('proposals').select('*'),supabase.from('agency_goals').select('*').eq('month_start', monthStart()).maybeSingle()]); if(p.data)setPayments(p.data as Payment[]);if(e.data)setExpenses(e.data as BusinessExpense[]);if(l.data)setLeads(l.data as Lead[]);if(pr.data)setProposals(pr.data as Proposal[]);if(g.data)setGoal(g.data as AgencyGoal); },[configured,supabase]);
  useEffect(()=>{load();},[load]);
  const stats = useMemo(()=>{const revenue=payments.filter(p=>p.status==='Tamamlandı'&&inCurrentMonth(p.paid_at)).reduce((s,p)=>s+Number(p.amount),0);const cost=expenses.filter(e=>e.status==='Ödendi'&&inCurrentMonth(e.expense_date)).reduce((s,e)=>s+Number(e.amount),0);const outcomes=leads.filter(l=>Boolean(l.contact_outcome));const interested=outcomes.filter(l=>l.contact_outcome==='İlgileniyor'||l.contact_outcome==='Teklif İstedi').length;const proposalRequests=outcomes.filter(l=>l.contact_outcome==='Teklif İstedi').length;const closed=leads.filter(l=>l.status==='Kazanıldı'||l.status==='Kaybedildi');const wins=leads.filter(l=>l.status==='Kazanıldı'&&inCurrentMonth(l.updated_at)).length;return {revenue,cost,net:revenue-cost,leads:leads.filter(l=>inCurrentMonth(l.created_at)).length,proposals:proposals.filter(p=>inCurrentMonth(p.created_at)).length,wins,outcomes:outcomes.length,interested,proposalRequests,closeRate:closed.length?Math.round(leads.filter(l=>l.status==='Kazanıldı').length/closed.length*100):0,missingEvidence:leads.filter(l=>!l.audit_checked_at&&!l.audit_sources).length};},[payments,expenses,leads,proposals]);
  const save = async (event:React.FormEvent)=>{event.preventDefault();if(!configured)return;const {error}=await supabase.from('agency_goals').upsert({month_start:goal.month_start,revenue_target:Number(goal.revenue_target)||0,new_lead_target:Number(goal.new_lead_target)||0,proposal_target:Number(goal.proposal_target)||0,notes:goal.notes||null},{onConflict:'month_start'});if(error)alert(`Hedef kaydedilemedi: ${error.message}`);else load();};
  const progress=(actual:number,target?:number)=>target?Math.min(100,Math.round(actual/Number(target)*100)):0;
  return <Shell><div className="space-y-6"><div><h1 className="text-2xl font-extrabold text-white">Aylık Hedefler & Raporlar</h1><p className="text-xs text-apex-muted mt-1">Hedefi elle belirleyin; ciro, gider, aday ve teklif sonuçları gerçek kayıtlardan hesaplansın.</p></div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[['Bu ay tahsilat',stats.revenue,'text-emerald-400'],['Bu ay gider',stats.cost,'text-red-400'],['Net sonuç',stats.net,stats.net>=0?'text-emerald-400':'text-red-400']].map(([label,value,color])=><div key={String(label)} className="bg-apex-card border border-apex-border rounded-xl p-5"><p className="text-[11px] text-apex-muted">{label}</p><p className={`text-2xl font-black mt-1 ${color}`}>{formatCurrency(Number(value))}</p></div>)}</div>
  <form onSubmit={save} className="bg-apex-card border border-apex-border rounded-xl p-5 grid grid-cols-1 md:grid-cols-4 gap-3 items-end"><div><label className="block text-xs text-apex-muted mb-1">Ay</label><input type="month" value={(goal.month_start||monthStart()).slice(0,7)} onChange={e=>setGoal(g=>({...g,month_start:`${e.target.value}-01`}))} className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"/></div><div><label className="block text-xs text-apex-muted mb-1">Tahsilat hedefi (₺)</label><input type="number" min="0" value={goal.revenue_target||''} onChange={e=>setGoal(g=>({...g,revenue_target:Number(e.target.value)}))} className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"/></div><div><label className="block text-xs text-apex-muted mb-1">Yeni aday / teklif hedefi</label><div className="grid grid-cols-2 gap-2"><input type="number" min="0" value={goal.new_lead_target||''} onChange={e=>setGoal(g=>({...g,new_lead_target:Number(e.target.value)}))} placeholder="Aday" className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"/><input type="number" min="0" value={goal.proposal_target||''} onChange={e=>setGoal(g=>({...g,proposal_target:Number(e.target.value)}))} placeholder="Teklif" className="w-full bg-apex-dark border border-apex-border rounded-lg text-white p-2.5"/></div></div><button className="flex justify-center gap-2 bg-apex-orange text-white text-xs font-bold p-2.5 rounded-lg"><Save className="w-4 h-4"/>Hedefi Kaydet</button></form>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{[['Tahsilat hedefi',stats.revenue,goal.revenue_target,formatCurrency(stats.revenue)],['Yeni aday hedefi',stats.leads,goal.new_lead_target,`${stats.leads} aday`],['Teklif hedefi',stats.proposals,goal.proposal_target,`${stats.proposals} teklif`]].map(([label,actual,target,display])=><div key={String(label)} className="bg-apex-card border border-apex-border rounded-xl p-4"><div className="flex justify-between text-xs"><span className="text-white font-bold">{label}</span><span className="text-apex-orange">%{progress(Number(actual),Number(target))}</span></div><div className="h-2 bg-apex-dark rounded mt-3 overflow-hidden"><div style={{width:`${progress(Number(actual),Number(target))}%`}} className="h-full bg-apex-orange"/></div><p className="text-[11px] text-apex-muted mt-2">Gerçekleşen: {display} · Hedef: {target || 0}</p></div>)}</div>
  <section className="bg-apex-card border border-apex-border rounded-xl p-5"><div className="flex flex-col md:flex-row md:items-end justify-between gap-2"><div><h2 className="font-bold text-white">Satış öğrenme panosu</h2><p className="text-[11px] text-apex-muted mt-1">Yalnızca kaydedilmiş arama sonuçlarına bakar; varsayım üretmez.</p></div><span className="text-[11px] text-amber-400">{stats.missingEvidence} adayda kaynaklı denetim eksik</span></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-4">{[['Sonuç kaydı',stats.outcomes],['İlgi / teklif sinyali',stats.interested],['Teklif talebi',stats.proposalRequests],['Kapanış oranı',`%${stats.closeRate}`]].map(([label,value])=><div key={String(label)} className="bg-apex-dark border border-apex-border rounded-lg p-3"><p className="text-[10px] text-apex-muted">{label}</p><p className="text-lg font-black text-apex-orange mt-1">{value}</p></div>)}</div><p className="text-[11px] text-apex-muted mt-4">Kullanım: Her arama/DM/e-posta sonrası sonucu aday kartından kaydedin. Birkaç hafta sonra hangi sektör, kanal ve teklif yaklaşımının daha çok ilgi getirdiğini bu kayıtlar üzerinden birlikte iyileştirebilirsiniz.</p></section>
  <div className="bg-apex-card border border-apex-border rounded-xl p-5 text-xs"><h2 className="font-bold text-white">Bu ay satış özeti</h2><p className="text-apex-muted mt-2">Kazanılan iş: <strong className="text-emerald-400">{stats.wins}</strong> · Bu değerler yalnızca kayıtlı işlem ve tarihlerden gelir; hedefe göre varsayım yapılmaz.</p></div>
  </div></Shell>;
}
